# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(820, 729)
        font = QtGui.QFont()
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.send_from = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.send_from.setGeometry(QtCore.QRect(10, 50, 271, 311))
        self.send_from.setStyleSheet("")
        self.send_from.setPlaceholderText("")
        self.send_from.setObjectName("send_from")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(13, 5, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(289, 5, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.send_to = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.send_to.setGeometry(QtCore.QRect(290, 50, 281, 311))
        self.send_to.setObjectName("send_to")
        self.file_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.file_1.setGeometry(QtCore.QRect(10, 622, 181, 33))
        self.file_1.setStyleSheet("")
        self.file_1.setObjectName("file_1")
        self.file_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.file_2.setGeometry(QtCore.QRect(200, 624, 181, 33))
        self.file_2.setStyleSheet("")
        self.file_2.setObjectName("file_2")
        self.file_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.file_3.setGeometry(QtCore.QRect(10, 664, 181, 33))
        self.file_3.setStyleSheet("")
        self.file_3.setObjectName("file_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(11, 593, 181, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.start_work = QtWidgets.QPushButton(self.centralwidget)
        self.start_work.setGeometry(QtCore.QRect(420, 560, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.start_work.setFont(font)
        self.start_work.setStyleSheet("")
        self.start_work.setObjectName("start_work")
        self.default_password = QtWidgets.QLineEdit(self.centralwidget)
        self.default_password.setGeometry(QtCore.QRect(420, 465, 141, 33))
        self.default_password.setStyleSheet("")
        self.default_password.setObjectName("default_password")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(420, 436, 151, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.file_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.file_4.setGeometry(QtCore.QRect(200, 664, 181, 33))
        self.file_4.setStyleSheet("")
        self.file_4.setObjectName("file_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(580, 10, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.logs_data = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.logs_data.setGeometry(QtCore.QRect(580, 50, 231, 651))
        self.logs_data.setStyleSheet("")
        self.logs_data.setPlainText("")
        self.logs_data.setPlaceholderText("")
        self.logs_data.setObjectName("logs_data")
        self.stop_work = QtWidgets.QPushButton(self.centralwidget)
        self.stop_work.setGeometry(QtCore.QRect(420, 610, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.stop_work.setFont(font)
        self.stop_work.setStyleSheet("")
        self.stop_work.setObjectName("stop_work")
        self.check_field = QtWidgets.QPushButton(self.centralwidget)
        self.check_field.setGeometry(QtCore.QRect(420, 510, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.check_field.setFont(font)
        self.check_field.setObjectName("check_field")
        self.field_status = QtWidgets.QLabel(self.centralwidget)
        self.field_status.setGeometry(QtCore.QRect(640, 650, 201, 17))
        self.field_status.setText("")
        self.field_status.setObjectName("field_status")
        self.messages_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.messages_text.setGeometry(QtCore.QRect(10, 440, 391, 141))
        self.messages_text.setObjectName("messages_text")
        self.message_subject = QtWidgets.QLineEdit(self.centralwidget)
        self.message_subject.setGeometry(QtCore.QRect(10, 390, 271, 33))
        self.message_subject.setObjectName("message_subject")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 370, 181, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 420, 190, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.attach_delay = QtWidgets.QLineEdit(self.centralwidget)
        self.attach_delay.setGeometry(QtCore.QRect(288, 390, 113, 33))
        self.attach_delay.setObjectName("attach_delay")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(290, 369, 281, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(410, 387, 151, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(410, 407, 151, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.captcha_api_key = QtWidgets.QLineEdit(self.centralwidget)
        self.captcha_api_key.setGeometry(QtCore.QRect(420, 662, 141, 33))
        self.captcha_api_key.setText("")
        self.captcha_api_key.setObjectName("captcha_api_key")
        self.file_1_button = QtWidgets.QPushButton(self.centralwidget)
        self.file_1_button.setGeometry(QtCore.QRect(103, 622, 88, 33))
        self.file_1_button.setObjectName("file_1_button")
        self.file_3_button = QtWidgets.QPushButton(self.centralwidget)
        self.file_3_button.setGeometry(QtCore.QRect(103, 664, 88, 33))
        self.file_3_button.setObjectName("file_3_button")
        self.file_2_button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.file_2_button_2.setGeometry(QtCore.QRect(293, 624, 88, 33))
        self.file_2_button_2.setObjectName("file_2_button_2")
        self.file_4_button = QtWidgets.QPushButton(self.centralwidget)
        self.file_4_button.setGeometry(QtCore.QRect(293, 664, 88, 33))
        self.file_4_button.setObjectName("file_4_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "mailer"))

        self.label.setText(_translate("MainWindow", "Откуда отправляем:"))
        self.label_2.setText(_translate("MainWindow", "Куда отправляем:"))

        self.file_1.setPlaceholderText(_translate("MainWindow", "file.pdf"))
        self.file_2.setPlaceholderText(_translate("MainWindow", "file2.png"))
        self.file_3.setPlaceholderText(_translate("MainWindow", "file3.jpg"))
        self.label_3.setText(_translate("MainWindow", "Название файлов вложения:"))
        self.start_work.setText(_translate("MainWindow", "Начать"))
        self.label_4.setText(_translate("MainWindow", "Общий пароль для почт:"))
        self.file_4.setPlaceholderText(_translate("MainWindow", "file4.pdf"))
        self.label_7.setText(_translate("MainWindow", "Информация:"))
        self.stop_work.setText(_translate("MainWindow", "Остановить"))
        self.check_field.setText(_translate("MainWindow", "Проверить поля"))
        self.label_5.setText(_translate("MainWindow", "Тема сообщений:"))
        self.label_8.setText(_translate("MainWindow", "Текст сообщений"))
        self.attach_delay.setText(_translate("MainWindow", "2"))
        self.label_9.setText(_translate("MainWindow", "Задержка перед отправкой файлов:"))
        self.label_10.setText(_translate("MainWindow", "Для картинок: 2-5 сек."))
        self.label_11.setText(_translate("MainWindow", "Для презентаций: 10-25 сек"))
        self.captcha_api_key.setPlaceholderText(_translate("MainWindow", "RuCaptcha api key"))
        self.file_1_button.setText(_translate("MainWindow", "Открыть"))
        self.file_3_button.setText(_translate("MainWindow", "Открыть"))
        self.file_2_button_2.setText(_translate("MainWindow", "Открыть"))
        self.file_4_button.setText(_translate("MainWindow", "Открыть"))

